services:
  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - 6379:6379

  # robot:
  #   build:
  #     context: ..
  #     dockerfile: docker/RobotDockerfile
  #   container_name: robot-container
  #   depends_on:
  #     - redis
  #   volumes:
  #     - volume_dump:/python_user/app/dump
  #   environment:
  #     - TF_VAR_DEGIRO_ACCOUNT={"user_token":, "int_account":, "username":"", "password":"", "totp_secret_key":""}

volumes:
  volume_dump:
